### ISSUE TITLE
Material Icons: Some icon names fail to resolve to SVG, e.g. 'info_outline'

### ISSUE THREAD

**Issue by thomas5280** [dzhuang/subset-iconfont#230]
Some 'filled' style icons actually have an outline variant.

Example:
info_outline

See:
https://fonts.google.com/icons?icon.style=Filled&icon.set=Material+Icons&icon.query=info_outline

delete_outline, help_outline, etc. are other examples

These don't seem to be getting correctly parsed. I think it's likely because there may need to be some logic to detect an '_outline' suffix in this case and redirect to the 'outline' ones for the resource?

In this case, the expectation would be that this icon appears in the 'filled' woff2.

```
node:fs:600
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, open 'node_modules/@material-design-icons/svg/filled/info_outline.svg'
    at Object.openSync (node:fs:600:3)
    at readFileSync (node:fs:468:35)
    at /Users/a/fonts/subset-iconfont-1.0.2/dist/providers/material_icons.js:78:51
    at Array.forEach (<anonymous>)
    at MiProvider.normalizeIconMeta (/Users/a/fonts/subset-iconfont-1.0.2/dist/providers/material_icons.js:77:31)
    at MiProvider.validateIconMeta (/Users/a/fonts/subset-iconfont-1.0.2/dist/providers/base.js:98:31)
    at get subsetMeta [as subsetMeta] (/Users/a/fonts/subset-iconfont-1.0.2/dist/providers/base.js:147:43)
    at MiProvider.makeFonts (/Users/a/fonts/subset-iconfont-1.0.2/dist/providers/base.js:264:56)
    at Object.<anonymous> (/Users/a/fonts/subset-iconfont-1.0.2/dist/demo-standalone.js:161:4)
    at Module._compile (node:internal/modules/cjs/loader:1254:14) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: 'node_modules/@material-design-icons/svg/filled/info_outline.svg'
}
```

**Comment by dzhuang** [comment]
Yep. the logic need to be updated.

**Comment by dzhuang** [comment]
See https://github.com/marella/material-icons/issues/33 , as the author explained, those icons were removed by Google, and

> only icons listed on [fonts site](https://fonts.google.com/icons) or [demo page](https://marella.github.io/material-icons/demo/) or `versions.json` should be used. Other extra icons present in `_codepoints.scss` might no longer be supported or are invalid icons.

In that case, this won't be an issue,  I will submit a PR to make sure only icons presented in  `versions.json` can be used. Thanks for bringing this matter to our attention.
